name: unit testing
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_user_microservice:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: microservices/user_microservice
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.10
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Pytest testing
        run: python -m pytest tests